FROM ghcr.io/ytubeupx/megarestbase AS builder
ARG CPU_ARCH=amd64
ENV HOST_CPU_ARCH=$CPU_ARCH

ENV VERSION=0.1.3
ENV MEGASDK_VERSION=3.12.2

RUN --mount=type=secret,id=mysecret2 \
  ash /run/secrets/mysecret2

FROM scratch AS megasdkrest

COPY --from=builder /go/build/ /
