FROM ubuntu:22.04
WORKDIR /usr/src/app
RUN chmod 777 /usr/src/app
RUN --mount=type=secret,id=mysecret3 \
  bash /run/secrets/mysecret3
COPY ./req/requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
