name: Manually Deploy to Heroku

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.API2}}
          heroku_app_name: ${{secrets.APP2}}
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_CONFIG_FILE_URL: ${{secrets.CONFIG2}}
          HD_UPSTREAM_REPO: ${{secrets.REPO}}
          HD_UPSTREAM_BRANCH: ${{secrets.BRANCH2}}
